#!/bin/sh

#     __                               
#    / /_  _________ _      ______ ___ 
#   / __ \/ ___/ __ \ | /| / / __ `__ \
#  / /_/ (__  ) /_/ / |/ |/ / / / / / /
# /_.___/____/ .___/|__/|__/_/ /_/ /_/ 
#          /_/                        
#
# bspwm configuration file
#
# Written by Nathanael Putro

# Launch hotkey daemon
sxhkd &

# Launch background setter
nitrogen --restore &

# Launch compositor
picom &

# Launch status bar
$HOME/.config/polybar/launch.sh &

# Lauch file manager daemon
spacefm --daemon-mode &

# Add default monitor and its workspaces
bspc monitor eDP-1 --reset-desktops tty1 code1 chat1 mail1 web1

# Add additional monitor and its workspaces if connected
if xrandr --query | grep "HDMI-2 connected"; then
    bspc monitor HDMI-2 --reset-desktops tty2 code2 chat2 mail2 web2
    bspc wm --reorder-monitors eDP-1 HDMI-2
else
    bspc monitor HDMI-2 --remove
    bspc wm --adopt-orphans
fi

# Appearance
bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set window rules
bspc rule --add Chromium desktop='^5' follow=on
bspc rule --add discord desktop='^3' follow=on
bspc rule --add firefox desktop='^5' follow=on
bspc rule --add Mailspring desktop='^4' follow=on
bspc rule --add Station desktop='^3' follow=on
bspc rule --add Zathura state=tiled
bspc rule --add zoom desktop='^3' follow=on
