#!/bin/sh

# Launch hotkey daemon
sxhkd &

# Launch background setter
nitrogen --set-scaled $HOME/backgrounds/geometric-black-red.jpg &

# Launch compositor
picom &

# Launch status bar
$HOME/.config/polybar/launch.sh &

# Add multiple monitors and workspaces
bspc monitor -d tty code mail chat web

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
