#!/bin/bash

#         __              __                    __                      __  
#   _____/ /_  ___  _____/ /__      ____  ___  / /__      ______  _____/ /__
#  / ___/ __ \/ _ \/ ___/ //_/_____/ __ \/ _ \/ __/ | /| / / __ \/ ___/ //_/
# / /__/ / / /  __/ /__/ ,< /_____/ / / /  __/ /_ | |/ |/ / /_/ / /  / ,<   
# \___/_/ /_/\___/\___/_/|_|     /_/ /_/\___/\__/ |__/|__/\____/_/  /_/|_|  
#
# Check network status
#
# Written by Nathanael Putro
# Adapted from Aditya Shakya's check-network script (https://github.com/adi1090x/polybar-themes/blob/master/polybar-5/scripts/check-network)

count=0
disconnected=""
wireless_connected=""
ethernet_connected=""

SSID_NAME=$(iwgetid -r)
ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 25
        else
            echo "$wireless_connected"; sleep 5
        fi
    else
        echo "$disconnected"; sleep 0.5
    fi
done
