#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -xoffset -10 -yoffset 32 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Sleep| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Sleep) systemctl -i suspend ;;
                *Logout) killall bspwm;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
