#!/bin/bash

#                    __      __           
#   __  ______  ____/ /___ _/ /____  _____
#  / / / / __ \/ __  / __ `/ __/ _ \/ ___/
# / /_/ / /_/ / /_/ / /_/ / /_/  __(__  ) 
# \__,_/ .___/\__,_/\__,_/\__/\___/____/  
#     /_/
#
# Check for package updates
#
# Written by Nathanael Putro
# Adapted from:
#   Aditya Shakya's updates script (https://github.com/adi1090x/polybar-themes/blob/master/polybar-5/scripts/updates.sh)
#   polybar-scripts' updates-pacman-aurhelper script (https://github.com/polybar/polybar-scripts/blob/master/polybar-scripts/updates-pacman-aurhelper/updates-pacman-aurhelper.sh)

BAR_ICON=""
NOTIFY_ICON=/usr/share/icons/Papirus/32x32/apps/system-software-update.svg

get_total_updates() {
    if ! UPDATES_arch=$(checkupdates 2> /dev/null | wc -l ); then
        UPDATES_arch=0
    fi
    
    if ! UPDATES_aur=$(yay -Qum 2> /dev/null | wc -l); then
        UPDATES_aur=0
    fi

    UPDATES=$(("$UPDATES_arch" + "$UPDATES_aur"))
}

while true; do
    get_total_updates

    # notify user of updates
    if hash notify-send &>/dev/null; then
        if (( UPDATES > 50 )); then
            notify-send -u critical -i $NOTIFY_ICON \
                "You really need to update!!" "$UPDATES New packages"
        elif (( UPDATES > 25 )); then
            notify-send -u normal -i $NOTIFY_ICON \
                "You should update soon" "$UPDATES New packages"
        elif (( UPDATES > 2 )); then
            notify-send -u low -i $NOTIFY_ICON \
                "$UPDATES New packages"
        fi
    fi

    # when there are updates available
    # every 10 seconds another check for updates is done
    while (( UPDATES > 0 )); do
        if (( UPDATES == 1 )); then
            echo " $UPDATES Update"
        elif (( UPDATES > 1 )); then
            echo " $UPDATES Updates"
        else
            echo $BAR_ICON
        fi
        sleep 10
        get_total_updates
    done

    # when no updates are available, use a longer loop, this saves on CPU
    # and network uptime, only checking once every 30 min for new updates
    while (( UPDATES == 0 )); do
        echo $BAR_ICON
        sleep 1800
        get_total_updates
    done
done
